Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -8,17 +8,31 @@ jobs:
     runs-on: ubuntu-latest
     environment: release
     steps:
-      - name: Checkout Repository
+      - name: Check branch
+        if: ${{ github.ref != 'refs/heads/master' }}
+        run: echo "Invalid branch. This action can only be run on the master branch." && exit 1
+
+      - name: Checkout presto source
         uses: actions/checkout@v4
         with:
+          token: ${{ secrets.PRESTODB_CI_TOKEN }}
           fetch-depth: 0
           fetch-tags: true
-          token: ${{ secrets.PRESTODB_CI_TOKEN }}
+          ref: master
+          show-progress: false
 
-      - name: Configure Git
+      - name: Set up JDK 11
+        uses: actions/setup-java@v4
+        with:
+          java-version: '11'
+          distribution: 'temurin'
+
+      - name: Configure git
         run: |
-          git config --global user.email "ci@list.prestodb.io"
+          git config --global --add safe.directory ${{github.workspace}}
+          git config --global user.email "ci@lists.prestodb.io"
           git config --global user.name "prestodb-ci"
+          git config pull.rebase false
 
       - name: Setup GPG Keys
         env:
